import type { Collection, Product } from './types'

export const products: Product[] = [
  {
    id: 'p-001',
    slug: 'bague-eclat',
    name: 'Bague Éclat',
    collection: 'Origine',
    category: 'bagues',
    style: 'Organique',
    budget: '300-500',
    occasion: ['Fiançailles', 'Cadeau'],
    priceLabel: 'Sur demande',
    materials: ['Or 18k', 'Diamant brut'],
    status: 'available',
    description: "Une bague lumineuse aux lignes organiques, façonnée autour d'un diamant brut choisi pour ses reflets doux.",
    tags: ['Nouveauté', 'Fait main'],
    image: '/demo/bijoux-artisanaux/product-eclat.jpg',
    options: {
      sizes: ['50', '52', '54', '56'],
      materials: ['Or jaune 18k', 'Or rose 18k'],
    },
    details: {
      materials: 'Or 18 carats et diamant brut serti à la main.',
      size: "Disponible sur demande du 50 au 56. Ajustement possible après échange avec l'atelier.",
      care: 'Évitez les parfums et rangez la pièce dans son écrin après chaque port.',
    },
    featured: true,
    palette: 'linear-gradient(135deg, #efe2cf, #d9b4ab, #fdf8f7)',
  },
  {
    id: 'p-002',
    slug: 'collier-aube-tissee',
    name: 'Collier Aube Tissée',
    collection: 'Aube',
    category: 'colliers',
    style: 'Délicat',
    budget: '100-300',
    occasion: ['Pour moi', 'Cadeau'],
    priceLabel: 'À partir de 145 €',
    materials: ['Plaqué or 18k', 'Laiton texturé'],
    status: 'made_to_order',
    description: 'Inspiré par les premiers rayons de lumière, ce collier tressé à la main épouse délicatement la peau.',
    tags: ['Édition limitée', 'Sur mesure possible'],
    image: '/demo/bijoux-artisanaux/product-aube.jpg',
    options: {
      sizes: ['40 cm', '45 cm'],
      materials: ['Plaqué or 18k', 'Argent 925'],
    },
    details: {
      materials: 'Plaqué or 18 carats sur base laiton, détails martelés à la main.',
      size: "Longueur ajustable de 40 cm à 45 cm. Pendentif d'environ 1,5 cm.",
      care: "Évitez l'eau, les parfums et les cosmétiques. Nettoyez doucement avec une chamoisine sèche.",
    },
    featured: true,
    palette: 'linear-gradient(135deg, #f2e8d5, #fff, #a3ad9e)',
  },
  {
    id: 'p-003',
    slug: 'creoles-rosee',
    name: 'Créoles Rosée',
    collection: 'Rosée',
    category: 'boucles-oreilles',
    style: 'Minimaliste',
    budget: '100-300',
    occasion: ['Cadeau', 'Pour moi'],
    priceLabel: '210 €',
    materials: ['Or martelé 18k'],
    status: 'available',
    description: 'Des créoles légères et texturées, pensées pour capter la lumière sans jamais dominer le visage.',
    tags: ['Petite série'],
    image: '/demo/bijoux-artisanaux/product-rosee.jpg',
    options: {
      materials: ['Or martelé 18k', 'Argent 925'],
    },
    details: {
      materials: 'Or 18 carats martelé à la main, fermoir discret.',
      size: 'Diamètre de 22 mm. Port léger pour le quotidien.',
      care: 'Rangez séparément pour préserver la texture martelée.',
    },
    featured: true,
    palette: 'linear-gradient(135deg, #f7f3f1, #d4af37, #fdf8f7)',
  },
  {
    id: 'p-004',
    slug: 'bracelet-sylve',
    name: 'Bracelet Sylve',
    collection: 'Essentiel',
    category: 'bracelets',
    style: 'Organique',
    budget: '100-300',
    occasion: ['Pour moi', 'Anniversaire'],
    priceLabel: '175 €',
    materials: ['Argent 925', 'Émeraude brute'],
    status: 'sold_out',
    description: "Un bracelet fin inspiré des feuillages, ponctué d'une pierre brute aux nuances vertes et profondes.",
    tags: ['Pièce indisponible'],
    image: '/demo/bijoux-artisanaux/product-lueur.jpg',
    options: {
      sizes: ['16 cm', '18 cm'],
      materials: ['Argent 925'],
    },
    details: {
      materials: 'Argent 925 et émeraude brute sélectionnée en petite série.',
      size: 'Longueur 16 à 18 cm selon ajustement.',
      care: "Gardez la pierre à l'abri des chocs et de l'humidité prolongée.",
    },
    featured: false,
    palette: 'linear-gradient(135deg, #a3ad9e, #fff, #f2e8d5)',
  },
  {
    id: 'p-005',
    slug: 'bague-lune-douce',
    name: 'Bague Lune Douce',
    collection: 'Saison',
    category: 'bagues',
    style: 'Poétique',
    budget: '100-300',
    occasion: ['Cadeau', 'Pour moi'],
    priceLabel: 'Prix à confirmer',
    materials: ['Argent 925', 'Pierre de lune'],
    status: 'preorder',
    description: "Une bague en préparation, pensée autour d'une pierre laiteuse et d'un serti discret travaillé à la main.",
    tags: ['À venir', 'Demande possible'],
    image: '/demo/bijoux-artisanaux/product-ombre.jpg',
    options: {
      sizes: ['52', '54', '56'],
      materials: ['Argent 925'],
    },
    details: {
      materials: 'Argent 925 et pierre de lune, sous réserve de sélection finale des pierres.',
      size: 'Tailles envisagées de 52, 54 et 56.',
      care: 'Les conseils définitifs seront confirmés lorsque la pièce sera finalisée.',
    },
    featured: false,
    palette: 'linear-gradient(135deg, #fdf8f7, #e6e1e0, #d9b4ab)',
  },
  {
    id: 'p-006',
    slug: 'boucles-nacre-claire',
    name: 'Boucles Nacre Claire',
    collection: 'Lumière',
    category: 'boucles-oreilles',
    style: 'Délicat',
    budget: '100-300',
    occasion: ['Pour moi', 'Cadeau'],
    priceLabel: '190 €',
    materials: ['Nacre naturelle', 'Argent 925'],
    status: 'available',
    description: "Des boucles d'oreilles délicates et lumineuses, mariant la douceur de la nacre naturelle à l'éclat de l'argent 925.",
    tags: ['Fait main', 'Nacre naturelle'],
    image: '/demo/bijoux-artisanaux/product-nacre.jpg',
    options: {
      materials: ['Argent 925'],
    },
    details: {
      materials: 'Nacre naturelle et argent 925.',
      size: "Diamètre d'environ 15 mm. Très légères à porter.",
      care: "Nettoyer doucement avec un chiffon doux, éviter le contact prolongé avec l'eau.",
    },
    featured: false,
    palette: 'linear-gradient(135deg, #fdf8f7, #efe2cf, #d9b4ab)',
  },
  {
    id: 'p-007',
    slug: 'collier-fil-dor',
    name: "Collier Fil d'Or",
    collection: 'Origine',
    category: 'colliers',
    style: 'Minimaliste',
    budget: '100-300',
    occasion: ['Pour moi', 'Cadeau'],
    priceLabel: 'À partir de 160 €',
    materials: ['Plaqué or 18k', 'Pendentif martelé'],
    status: 'made_to_order',
    description: "Un collier d'une grande finesse avec son pendentif martelé à la main suspendu à une chaîne en plaqué or 18 carats.",
    tags: ['Martelé main', 'Sur commande'],
    image: '/demo/bijoux-artisanaux/product-fil-or.jpg',
    options: {
      sizes: ['40 cm', '45 cm'],
      materials: ['Plaqué or 18k'],
    },
    details: {
      materials: 'Chaîne fine en plaqué or 18 carats, pendentif en laiton martelé.',
      size: 'Longueur de chaîne de 40 cm avec rallonge de 5 cm.',
      care: 'Conserver au sec, essuyer après chaque utilisation.',
    },
    featured: false,
    palette: 'linear-gradient(135deg, #f2e8d5, #f7f3f1, #efe2cf)',
  },
  {
    id: 'p-008',
    slug: 'bague-rosee-minerale',
    name: 'Bague Rosée Minérale',
    collection: 'Rosée',
    category: 'bagues',
    style: 'Organique',
    budget: '100-300',
    occasion: ['Pour moi', 'Cadeau'],
    priceLabel: '230 €',
    materials: ['Quartz rose', 'Laiton texturé'],
    status: 'available',
    description: "Une bague en laiton texturé couronnée d'un délicat quartz rose poli aux reflets translucides.",
    tags: ['Pièce unique', 'Quartz rose'],
    image: '/demo/bijoux-artisanaux/product-rosee-min.jpg',
    options: {
      sizes: ['52', '54', '56'],
      materials: ['Laiton texturé', 'Argent 925'],
    },
    details: {
      materials: 'Quartz rose naturel serti sur anneau en laiton texturé.',
      size: 'Disponible en tailles 52, 54 et 56. Autres tailles sur demande.',
      care: "Évitez l'exposition prolongée au soleil et aux produits chimiques.",
    },
    featured: false,
    palette: 'linear-gradient(135deg, #efe2cf, #d9b4ab, #fdf8f7)',
  },
  {
    id: 'p-009',
    slug: 'bracelet-eclat-sable',
    name: 'Bracelet Éclat Sable',
    collection: 'Saison',
    category: 'bracelets',
    style: 'Délicat',
    budget: '100-300',
    occasion: ['Pour moi', 'Cadeau'],
    priceLabel: 'Prix à confirmer',
    materials: ['Perles naturelles', 'Fermoir doré'],
    status: 'preorder',
    description: 'Un bracelet élégant composé de perles naturelles rythmées par un fermoir doré artisanal.',
    tags: ['Bientôt disponible', 'Nouveauté'],
    image: '/demo/bijoux-artisanaux/product-eclat-sable.jpg',
    options: {
      sizes: ['16 cm', '18 cm'],
      materials: ['Fermoir plaqué or'],
    },
    details: {
      materials: "Perles naturelles d'eau douce et fermoir en laiton doré à l'or fin.",
      size: 'Longueur ajustable de 16 cm à 18 cm.',
      care: "Ne pas immerger sous l'eau, nettoyer avec un tissu doux.",
    },
    featured: false,
    palette: 'linear-gradient(135deg, #a3ad9e, #f7f3f1, #f2e8d5)',
  },
]

export const collections: Collection[] = [
  {
    id: 'all',
    label: 'Toutes les créations',
    category: null,
    description: "Toutes les pièces visibles de l'atelier.",
  },
  {
    id: 'rings',
    label: 'Bagues',
    category: 'bagues',
    description: 'Bagues artisanales, pièces uniques ou petites séries.',
  },
  {
    id: 'necklaces',
    label: 'Colliers',
    category: 'colliers',
    description: 'Colliers délicats et pendentifs façonnés à la main.',
  },
  {
    id: 'earrings',
    label: "Boucles d'oreilles",
    category: 'boucles-oreilles',
    description: 'Créoles et boucles légères aux textures organiques.',
  },
  {
    id: 'bracelets',
    label: 'Bracelets',
    category: 'bracelets',
    description: 'Bracelets fins pour le quotidien et les cadeaux intimes.',
  },
]

export function getProduct(slug: string) {
  return products.find((product) => product.slug === slug)
}
